### ISSUE TITLE
Performance drop (on RPI3) after release 1.12

### ISSUE THREAD

**Issue by kauailabs** [stevedesmond-ca/vscode-arm#1]
I started out at w/vscode on [headmelted's packageio site](https://packagecloud.io/headmelted/codebuilds).  Latest version there is 1.14.  On RPI3 (I'm using the new RPI 3B+) was actually pretty good.

But because of needing to install an extension that needed a later version of vscode, I had to go elsewhere.

In addition to building vscode from source myself and running it (1.21.2), I have also installed each of the deb packages from the releases section of this site.

V. 1.12 on your release section gives very similar performance to 1.14 from the headmelted site.

But the next version in the releases (V1.18) shows significantly degraded performance (and the same is true for the other releases).

My hunch is the underlying Electron UI components have an issue, but I'm not sure.  I realize this isn't necessarily a build problem, but wanted to check w/you as I'm trying to figure out what's changed, and thought perhaps a build setting could be involved.

**Comment by SteveDesmond-ca** [comment]
Yeah, there have been a couple points since 1.12 when underlying functionality has been swapped out / expanded, so my expectation is that it's doing much more under the hood now. My advice would be to get some before+after profiling snapshots and open an issue on the official repo. My guess is that they're not actively testing on unsupported hardware like ARM, as yarn (introduced in 1.19 to replace npm) doesn't even support cross-compiling.
