### ISSUE TITLE
How to install latest build?

### ISSUE THREAD

**Issue by muddyraven** [stevedesmond-ca/vscode-arm#3]
Hi Steve, I'm new to git so I am looking for help installing this build of vs code on my Raspberry Pi. I've been using headmelted's 1.14 build to learn webdev but it is outdated somewhat. Do I simply follow the steps in the setup folder, or do I need to build first? I have searched for answers but haven't found any.

Adam

**Comment by SteveDesmond-ca** [comment]
`.deb` builds are available under [Releases](https://github.com/stevedesmond-ca/vscode-arm/releases), which should be runnable on Debian, Raspbian, Ubuntu, etc. by double-clicking or running `sudo dpkg -i {downloaded .deb}`

I believe 1.21.1 is the latest. There's been a lot of under-the-hood changes since then, so later versions don't build with the same scripts, but it's on my list to get back up to date.

My plan is to be able to submit a `Dockerfile` to the official vscode repo once the build is working again, so they can hopefully include ARM in their CI process.

**Comment by muddyraven** [comment]
Thanks for the assistance Steve, it's greatly appreciated!

Great work on the builds, my 10 year old daughter and me are able to do so much on our Raspberry Pis thanks to you, Jay and all involved.

**Comment by SteveDesmond-ca** [comment]
Glad to be of service -- happy coding!
